// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAih55v4yszRZFnB25ZHq-TbbcEWMF4gHs',
    appId: '1:1056766311552:web:54e3448c082e5ba2fb3a65',
    messagingSenderId: '1056766311552',
    projectId: 'zakirvai',
    authDomain: 'zakirvai.firebaseapp.com',
    storageBucket: 'zakirvai.appspot.com',
    measurementId: 'G-90970EK25N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglKMMQg1uxHw68NwpWZ_UlfFUgsf4kxw',
    appId: '1:1056766311552:android:3283a384e46132cafb3a65',
    messagingSenderId: '1056766311552',
    projectId: 'zakirvai',
    storageBucket: 'zakirvai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiybNYTkMEFEVUVDHRrhCiRzyK1UWxEuk',
    appId: '1:1056766311552:ios:b4e38881c548ab0efb3a65',
    messagingSenderId: '1056766311552',
    projectId: 'zakirvai',
    storageBucket: 'zakirvai.appspot.com',
    iosBundleId: 'com.example.islamicMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiybNYTkMEFEVUVDHRrhCiRzyK1UWxEuk',
    appId: '1:1056766311552:ios:b4e38881c548ab0efb3a65',
    messagingSenderId: '1056766311552',
    projectId: 'zakirvai',
    storageBucket: 'zakirvai.appspot.com',
    iosBundleId: 'com.example.islamicMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAih55v4yszRZFnB25ZHq-TbbcEWMF4gHs',
    appId: '1:1056766311552:web:e52c8f992170edbefb3a65',
    messagingSenderId: '1056766311552',
    projectId: 'zakirvai',
    authDomain: 'zakirvai.firebaseapp.com',
    storageBucket: 'zakirvai.appspot.com',
    measurementId: 'G-YEZKD6HH9N',
  );

}