// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk98FIyxI5ifh-dP1Yrv0qLOEYRao43lo',
    appId: '1:349567200503:web:c864ada120bbf04b9d37f2',
    messagingSenderId: '349567200503',
    projectId: 'islamic-media-8b317',
    authDomain: 'islamic-media-8b317.firebaseapp.com',
    storageBucket: 'islamic-media-8b317.appspot.com',
    measurementId: 'G-0K4Q3MZ72D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUHyJeUM3SGyYbhCMacXJWBPFqReR3uE',
    appId: '1:349567200503:android:db72eeab39ff32299d37f2',
    messagingSenderId: '349567200503',
    projectId: 'islamic-media-8b317',
    storageBucket: 'islamic-media-8b317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqCgPji5uM8EBnoyCOte9luYo8oE2vi0',
    appId: '1:349567200503:ios:372ef464f4c153539d37f2',
    messagingSenderId: '349567200503',
    projectId: 'islamic-media-8b317',
    storageBucket: 'islamic-media-8b317.appspot.com',
    iosBundleId: 'com.example.islamicMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqCgPji5uM8EBnoyCOte9luYo8oE2vi0',
    appId: '1:349567200503:ios:372ef464f4c153539d37f2',
    messagingSenderId: '349567200503',
    projectId: 'islamic-media-8b317',
    storageBucket: 'islamic-media-8b317.appspot.com',
    iosBundleId: 'com.example.islamicMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk98FIyxI5ifh-dP1Yrv0qLOEYRao43lo',
    appId: '1:349567200503:web:dd0a003a467b75739d37f2',
    messagingSenderId: '349567200503',
    projectId: 'islamic-media-8b317',
    authDomain: 'islamic-media-8b317.firebaseapp.com',
    storageBucket: 'islamic-media-8b317.appspot.com',
    measurementId: 'G-NRZB75FEJT',
  );
}
